import { provideHttpClient } from '@angular/common/http';
import { provideRouter } from '@angular/router';
import { provideNoopAnimations } from '@angular/platform-browser/animations';
import { TranslateModule } from '@ngx-translate/core';

/**
 * Shared test providers for component specs.
 *
 * Almost every component in this project depends directly or indirectly
 * (via NavigationService, RouterModule/routerLink, TranslateModule, or
 * MatDialogModule) on Router, HttpClient, or animations. The test files
 * generated by `ng generate component` do not provide these dependencies
 * by default, which previously caused NullInjectorError failures in each test.
 *
 * Instead of repeating this setup in every *.component.spec.ts file,
 * these providers are defined centrally here.
 *
 * No explicit type annotation is used: provideHttpClient(), provideRouter()
 * return `EnvironmentProviders`, and provideNoopAnimations() returns `Provider[]`.
 * TestBed.providers accepts a mixed array, so TypeScript is allowed to infer
 * the union type automatically.
 */
export const commonTestProviders = [
  provideHttpClient(),
  provideRouter([]),
  provideNoopAnimations(),
];

/**
 * TranslateModule.forRoot() registers TranslateStore and related services.
 * Without an explicit loader, ngx-translate falls back to a fake loader,
 * which prevents real HTTP requests — ideal for unit tests.
 */
export const commonTestImports = [
  TranslateModule.forRoot(),
];
